### ISSUE TITLE
Test Harness Vat Line 

### ISSUE THREAD

**Issue by andy8052** [makerdao/mkr-mcd-spec#194]
The test harness code being generated seems to always use `Line` when calling `file` in the `vat`. While `Line` is correct for a 2 parameter `file` call, it should be `line` when call with 3. This can be seen [here](https://github.com/makerdao/dss/blob/master/src/vat.sol#L134). I looked at the python code to change it myself but it will probably take someone on the RV team 1/10 the time as I have not really ever looked at this python code. Happy to dive in though if we want me to.

**Comment by kmbarry1** [comment]
cc @ehildenb 

Yeah, the `K` code is correct, seems to be an issue with the Solidity generation instead.
