### ISSUE TITLE
Clear documentation around dependencies, packaging, and architecture

### ISSUE THREAD

**Issue by WilfredTA** [makerdao/mkr-mcd-spec#224]
There should be a clear set of documentation around which libraries & packages depend on what and why.

Each package should be easy to use and set up, with installation instructions up to date

This applies to  the repos:

- [ ] https://github.com/kframework/evm-semantics
- [ ] https://github.com/makerdao/klab
- [ ] https://github.com/makerdao/k-dss
- [ ] https://github.com/makerdao/mkr-mcd-spec

Assume that a use knows how to do proofs (on paper for example).

Provide:

- [ ] Map of all the relevant repos, and overall project goal architecture (image from the engagement document).
- [ ] Explanation of how everything "works" or "fits together", to answer the question "what does this effort actually mean about the security of this system?"
- [ ] End-to-end instructions for how to get started with writing specs with KLab (start from Solidity code, writing the ACT spec, and then verifying the bytecode).

**Comment by ehildenb** [comment]
Assume that a use knows how to do proofs (on paper for example).

Provide:

- [ ] Map of all the relevant repos, and overall project goal architecture (image from the engagement document).
- [ ] Explanation of how everything "works" or "fits together", to answer the question "what does this effort actually mean about the security of this system?"
- [ ] Audited instructions for setup of all the relevant repos.
- [ ] End-to-end instructions for how to get started with writing specs with KLab (start from Solidity code, writing the ACT spec, and then verifying the bytecode).
