### ISSUE TITLE
Audit the documentation generated in #224

### ISSUE THREAD

**Issue by ehildenb** [makerdao/mkr-mcd-spec#226]
Make sure you can (record anywhere that there is confusion):

- [x] Install KEVM on a fresh container following instructions.
- [x] Build KLab and run the SafeAdd example following the instructions.
- [ ] Build the k-dss repo and run the proofs there following the instructions.
- [x] Build the mkr-mcd-spec repo and run the tests there following the instructions.

**Comment by anvacaru** [comment]
I was able to install KEVM on a fresh container, Build Klab and run the SafeAdd example.
I was also able to build the `mkr-mcd-spec` repo and run the example 
`./kmcd run --backend llvm tests/attacks/lucash-flip-end.mcd`


While following the instructions of the `k-dss` repo, I encountered the following error.
```
error: dapp --version
make: dapp: Command not found
recipe for target 'dapp' Failed
````
 Also, there is no `prove` rule in the main `Makefile` of the repository.
There is a typo in :

Make sure that KLAB_EVMS_PATH is setup to include $(pwd)/deps/~~evm-semanticss~~ evm-semantics.
